# Generated by Django 4.0.3 on 2022-03-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('offer_discount', 'Can offer product discount'),), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
